{% set name = "nodimo" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18d996bccf816b6f45e6769d9c131c084528321b913707eb02b65b5bae6c5e41
  md5: cf7711ee935e322aff0764fb1a258fc3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0.0
  run:
    - python >=3.9
    - sympy >=1.7

test:
  imports:
    - nodimo
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/rodrigopcastro018/nodimo/blob/main/LICENSE
  home: https://github.com/rodrigopcastro018/nodimo
  dev_url: https://github.com/rodrigopcastro018/nodimo
  doc_url: https://nodimo.readthedocs.io/
  summary: 'Nodimo is a tool that creates dimensionless models'
  description: >
    The main purpose of Nodimo is to transform a dimensional relationship
    between quantities into a dimensionless one. This is done by grouping
    dimensional quantities into dimensionless products in such a way that
    the resulting number of products is always lower than or equal to the
    starting number of quantities. Therefore, the ensuing dimensionless
    model is, at the same time, a generalization and simplification of the
    dimensional model.

extra:
  recipe-maintainers:
    - rodrigopcastro018
